# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QJWo7kq2Hlm8ZSm3BNd0a1QDw1D-KV-U
"""

def remove_duplicate_in_list(mylist):
  return list( dict.fromkeys(mylist))

def find_position(s, ch):
  return [i for i, letter in enumerate(s) if letter == ch]

def patient_id(sample_name):
  return sample_name[ 0 : find_position(sample_name, '-')[1] ]

def mean_TPM_per_patient(heart_tpm):
  _per_patient = pd.DataFrame(index=heart_tpm.index)

  for patient in common_patient_list:
    samples = []
    for sample in heart_tpm.columns:
      if patient in sample: samples.append(sample)

    patient_expression = heart_tpm[samples]
    _per_patient[patient] = patient_expression.mean(axis=1)

  return _per_patient